// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJK1UmYPe6IIXKSQeIgVPiZXP-ZqNFFVk',
    appId: '1:181304568429:web:1c3d2824cb33f58108ed64',
    messagingSenderId: '181304568429',
    projectId: 'meeteam-647e8',
    authDomain: 'meeteam-647e8.firebaseapp.com',
    storageBucket: 'meeteam-647e8.appspot.com',
    measurementId: 'G-KBLMSE98T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-C7M13aZ6xXADFhijzM7tNXUUYWv9LpY',
    appId: '1:181304568429:android:57ed4d2acee99cff08ed64',
    messagingSenderId: '181304568429',
    projectId: 'meeteam-647e8',
    storageBucket: 'meeteam-647e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Yev5UIx0bDqfpN_V-Bjwu7wn3tyr8wQ',
    appId: '1:181304568429:ios:bf73b91f4fce4e2508ed64',
    messagingSenderId: '181304568429',
    projectId: 'meeteam-647e8',
    storageBucket: 'meeteam-647e8.appspot.com',
    iosClientId: '181304568429-75c9i2qkslvo5t7lbfj28ckkmht116ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetteam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0Yev5UIx0bDqfpN_V-Bjwu7wn3tyr8wQ',
    appId: '1:181304568429:ios:bf73b91f4fce4e2508ed64',
    messagingSenderId: '181304568429',
    projectId: 'meeteam-647e8',
    storageBucket: 'meeteam-647e8.appspot.com',
    iosClientId: '181304568429-75c9i2qkslvo5t7lbfj28ckkmht116ud.apps.googleusercontent.com',
    iosBundleId: 'com.example.meetteam',
  );
}
